# See https://github.com/periph/gohci
version: 1
workers:
- name: mbp
  checks:
  - cmd:
    - go
    - test
    - ./...
  - cmd:
    - ./hostextra/d2xx/test.sh
  - cmd:
    - go
    - install
    - ./cmd/...
  - cmd:
    - d2xx
  - cmd:
    - go
    - install
    - -tags
    - periphextra
    - periph.io/x/periph/cmd/gpio-list
    - periph.io/x/periph/cmd/headers-list
    - periph.io/x/periph/cmd/i2c-list
    - periph.io/x/periph/cmd/spi-list
  - cmd:
    - gpio-list
  - cmd:
    - headers-list
  - cmd:
    - i2c-list
  - cmd:
    - spi-list
- name: raspberrypi-2f34
  checks:
  - cmd:
    - go
    - test
    - ./...
  - cmd:
    - go
    - install
    - ./cmd/...
  - cmd:
    - d2xx
- name: win10
  checks:
  - cmd:
    - go
    - test
    - -race
    - ./...
  - cmd:
    - go
    - vet
    - ./...
  - cmd:
    - go
    - install
    - ./cmd/...
  - cmd:
    - d2xx
  - cmd:
    - go
    - install
    - -tags
    - periphextra
    - periph.io/x/periph/cmd/gpio-list
    - periph.io/x/periph/cmd/headers-list
    - periph.io/x/periph/cmd/i2c-list
    - periph.io/x/periph/cmd/spi-list
  - cmd:
    - gpio-list
  - cmd:
    - headers-list
  - cmd:
    - i2c-list
  - cmd:
    - spi-list
